"""Curated arsenal catalog — CLI-runnable tools from the pipeline toolkit,
mapped to the phase they serve. Used by `arsenal.detect` to report what is
actually installed on the box. This is intentionally the *runnable subset* of
the full 630-tool reference (GUI/web/API-only entries are omitted).

Each entry: binary name on PATH -> short description.
"""
from __future__ import annotations

CATALOG: dict[str, dict[str, str]] = {
    "recon": {
        "nmap": "network/port/service scanner",
        "masscan": "mass IP port scanner",
        "zmap": "internet-wide scanner",
        "rustscan": "fast port scanner",
        "naabu": "port scanner (ProjectDiscovery)",
        "nuclei": "template-based vuln scanner",
        "httpx": "HTTP probing toolkit",
        "subfinder": "subdomain discovery",
        "amass": "subdomain enumeration (OWASP)",
        "sublist3r": "subdomain enumeration",
        "assetfinder": "domain/asset discovery",
        "findomain": "subdomain discovery",
        "dnsx": "DNS toolkit",
        "dnsrecon": "DNS enumeration",
        "dnsenum": "DNS enumeration",
        "fierce": "DNS recon",
        "whatweb": "website fingerprinting",
        "wafw00f": "WAF fingerprinting",
        "theHarvester": "email/subdomain OSINT",
        "recon-ng": "web recon framework",
        "spiderfoot": "OSINT automation",
        "sherlock": "username search",
        "holehe": "email-to-account correlation",
        "sublister": "subdomain enumeration",
    },
    "ingest": {
        "curl": "HTTP/S transfer",
        "wget": "HTTP/S download",
        "httpie": "human-friendly HTTP client",
        "nc": "netcat TCP/UDP",
        "ncat": "enhanced netcat",
        "socat": "multipurpose relay",
        "tcpdump": "packet capture",
        "tshark": "CLI Wireshark",
        "hping3": "packet crafting",
        "mtr": "network diagnostics",
        "exiftool": "metadata extraction",
        "binwalk": "firmware analysis/extraction",
        "foremost": "file carving",
        "strings": "extract strings from binaries",
        "pdftotext": "PDF text extraction",
    },
    "analyze": {
        "ghidra": "reverse engineering framework",
        "radare2": "RE framework",
        "r2": "radare2 CLI",
        "gdb": "GNU debugger",
        "objdump": "binary object analysis",
        "readelf": "ELF analysis",
        "strace": "syscall tracer",
        "ltrace": "library call tracer",
        "yara": "malware pattern matching",
        "semgrep": "multi-language SAST",
        "bandit": "python security linter",
        "jq": "JSON processor",
        "yq": "YAML/XML processor",
        "rg": "ripgrep fast search",
        "fd": "fast file finder",
        "sqlite3": "SQLite CLI",
    },
    "exploit": {
        "sqlmap": "automated SQL injection",
        "commix": "command injection",
        "nikto": "web server scanner",
        "wpscan": "WordPress scanner",
        "joomscan": "Joomla scanner",
        "gobuster": "URL/DNS/vhost busting",
        "ffuf": "fast web fuzzer",
        "feroxbuster": "content discovery",
        "dirb": "directory brute-forcer",
        "dirsearch": "web path discovery",
        "wfuzz": "web fuzzer",
        "hydra": "network login brute-forcer",
        "medusa": "parallel login brute-forcer",
        "ncrack": "network auth cracker",
        "patator": "multi-protocol brute-forcer",
        "searchsploit": "Exploit-DB search",
        "msfconsole": "Metasploit framework",
        "msfvenom": "payload generation",
    },
    "pivot": {
        "crackmapexec": "post-exploitation swiss army knife",
        "netexec": "CME fork (active)",
        "evil-winrm": "WinRM shell",
        "enum4linux": "SMB/Samba enumeration",
        "enum4linux-ng": "SMB enumeration (ng)",
        "smbclient": "SMB client",
        "smbmap": "SMB share enumeration",
        "responder": "LLMNR/NBT-NS poisoner",
        "impacket-secretsdump": "credential dumping",
        "impacket-psexec": "remote execution",
        "kerbrute": "Kerberos brute-force",
    },
    "crack": {
        "hashcat": "GPU password recovery",
        "john": "CPU password cracking",
        "hashid": "hash type identifier",
        "hash-identifier": "hash type identifier",
        "crunch": "wordlist generator",
        "cewl": "wordlist from website",
    },
    "wireless": {
        "aircrack-ng": "WiFi capture/analysis",
        "airmon-ng": "monitor-mode control",
        "airodump-ng": "WiFi capture",
        "reaver": "WPS attack",
        "bully": "WPS brute-force",
        "kismet": "wireless detector",
    },
    "c2_tunnel": {
        "chisel": "TCP/UDP tunnel over HTTP",
        "ligolo-ng": "reverse tunneling",
        "socat": "relay/tunnel",
        "ssh": "secure shell / tunnels",
        "proxychains4": "proxy chaining",
        "sshuttle": "transparent proxy via SSH",
    },
    "evasion": {
        "tor": "anonymous network",
        "proxychains4": "force proxy on any app",
        "openvpn": "VPN client",
        "wg": "WireGuard",
        "openssl": "encryption toolkit",
        "gpg": "encryption & signing",
        "steghide": "image steganography",
        "age": "modern file encryption",
    },
    "forensic": {
        "volatility3": "memory forensics",
        "vol": "volatility CLI",
        "foremost": "file carving",
        "testdisk": "partition recovery",
        "photorec": "file recovery",
        "bulk_extractor": "forensic data extraction",
        "chkrootkit": "rootkit detection",
        "rkhunter": "rootkit hunter",
        "clamscan": "antivirus scan",
        "lynis": "system auditing",
    },
}
